### PR TITLE
First version

### PR DESCRIPTION
**Pull request by rjarry**
The API coverage is incomplete for now. Some opinionated choices were made for a more "pythonic" approach compared to the C library.

@michalvasko @rkrejci could you give me some feedback?

### CODE REVIEW

**Comment by rjarry** [comment]
Hi Michal,

> `cdefs.h` seems mostly like a copy of `sysrepo.h`, is there really no way of preventing this and somehow using `sysrepo.h` directly?

That would be easier indeed, however, `cdefs.h` also contains `extern "Python"` functions declarations:

https://github.com/sysrepo/sysrepo-python/blob/3d0b58a6b1777169fa95db7579ef3695c72e60a4/cffi/cdefs.h#L222-L224

that are bound to actual Python functions:

https://github.com/sysrepo/sysrepo-python/blob/3d0b58a6b1777169fa95db7579ef3695c72e60a4/sysrepo/subscription.py#L159-L160

This allows to pass "Python" callbacks to sysrepo functions:

https://github.com/sysrepo/sysrepo-python/blob/3d0b58a6b1777169fa95db7579ef3695c72e60a4/sysrepo/session.py#L203-L205

Also, [CFFI does not handle all C statements](https://cffi.readthedocs.io/en/latest/overview.html#what-actually-happened) so `sysrepo.h` would not be accepted by it.

> Also, as you mentioned the API is not complete (same goes for _libyang_ probably), would it make sense to include some details about what exactly is missing? But if it is clear from the source then I guess it is redundant, I am not able to judge that.

You're right, I'll add a paragraph regarding API coverage in `README.rst`.

> As for the code itself, seems okay to me looking at the examples. I just did not know whether there will be a dependency on _libyang_ but I see that there is. Should not be a problem, though, as the same is true for the current bindings.

Yes, not much choice here.

Thanks a lot for your feedback!

**Comment by michalvasko** [comment]
What will happen if what is in `cdefs.h` will not match `sysrepo.h`? Obviously, that would be an API change, which should be followed by major SO version increment, but still. Because you may be able to process `sysrepo.h` to some desired form but not sure if that is worth the trouble, just wondering.

Regards,
Michal

**Comment by rjarry** [comment]
If that happens, it will certainly imply that the python code needs to be changed too, so I prefer to have an explicit compiler error.

I want to add a SO version check too so that we do not get gcc complaining about missing symbols when building the bindings on an older version of sysrepo.

**Comment by michalvasko** [comment]
Okay, as long as there are some compiler errors (and not just runtime) and even an SO check, it should be fine.

**Pull request merged**
