### PR TITLE
Add notificaton support

### PR DESCRIPTION
**Pull request by ishidawataru**
ref) https://github.com/sysrepo/sysrepo-python/issues/10

### CODE REVIEW

**Comment by rjarry** [comment]
Thanks @ishidawataru 

@nicolasmorini if you take it from here, I'd prefer if we only support the `sr_*_notif_*_tree` API and omit the sysrepo value API (which does not use libyang values).

**Comment by roberto-torre** [comment]
Hi @ishidawataru 

Thanks a lot for the provided patch. I am planning to extend it to see if it can be merged.

I have a couple of questions that you may help me with:

- Do you have a code snippet where you use the notifications feature? Could you please share it?
- Do you have a similar patch for libyang? I think that some notification support is needed to be able to send a notification.

Thanks!

**Comment by ishidawataru** [comment]
@roberto-torre You're right. Here is the patch for libyang. https://github.com/microsonic/goldstone-mgmt/blob/master/patches/libyang-python/notification.patch

The application code is not open-sourced yet. But it's really straightforward to use.

sender

```python
dnode = ly_ctx.parse_data_mem(n, fmt="json", notification=True)
session.notification_send_ly(dnode)
```

receiver

```python
session.subscribe_notification_tree(<model name>, <XPATH>, 0, 0, <python callback>)
```

**Comment by nicolasmorini** [comment]
Hi @rjarry and @ishidawataru! Just to keep you updated, @roberto-torre did most of the required work for this pull-request, but before being able to upload that here, we need to clarify some legal aspects with our current employer to be on the clear. I expect this will take at least a few more weeks.

We will keep you posted. Greetings!

**Comment by nicolasmorini** [comment]
Follow-ups of this pull-request:

- https://github.com/sysrepo/sysrepo-python/pull/16
- https://github.com/CESNET/libyang-python/pull/26

Thanks @ishidawataru for providing the initial code! (and apologies for the delay in getting this done)

**Comment by rjarry** [comment]
I'll close this one, let's continue on #16.

**Pull request closed without merging**
